# All Available EPL Leagues

In [2]:
# Import packages
import json
import os
import pandas as pd
import pymongo
import requests
from classes.progress_bar import printProgressBar

# Get the API details from the conda environment
headers = {
    'x-rapidapi-host': os.environ.get("api_host"),
    'x-rapidapi-key': os.environ.get("api_key")
}

def api_call(url):
    '''
    Call the given url and load the resulting JSON object

    Parameters
    ----------
    url: string
        The API endpoint to call with a GET request
    '''
    response = requests.request("GET", url, headers=headers)

    try:
        response = json.loads(response.text)
    except BaseException:
        print(f"Response {response.text} isn't valid JSON format.")

    return(response)

In [4]:
all_leagues = api_call("https://api-football-v1.p.rapidapi.com/v2/leagues")

In [12]:
pl = [{'season': x['season'],
  'start': x['season_start'], 
  'end': x['season_start'], 
  'available_coverage':x['coverage']} for x in all_leagues['api']['leagues'] if x['name'] == 'Premier League' and x['country'] == 'England']

In [20]:
pldf = pd.DataFrame(pl)
pldf.sort_values('season', inplace=True)

In [29]:
fixturedf = pldf.available_coverage.apply(pd.Series).fixtures.apply(pd.Series)
fixturedf.columns = ['fixture_' + x for x in fixturedf.columns]

In [30]:
pd.concat([pldf.drop('available_coverage', axis = 1), 
           pldf.available_coverage.apply(pd.Series).drop('fixtures', axis = 1),
           fixturedf], axis = 1)

,season,start,end,standings,players,topScorers,predictions,odds,fixture_events,fixture_lineups,fixture_statistics,fixture_players_statistics
9,2010,2010-08-14,2010-08-14,True,True,True,True,False,True,True,False,False
8,2011,2011-08-13,2011-08-13,True,True,True,True,False,True,True,False,False
7,2012,2012-08-18,2012-08-18,True,True,True,True,False,True,True,False,False
6,2013,2013-08-17,2013-08-17,True,True,True,True,False,True,True,False,False
5,2014,2014-08-16,2014-08-16,True,True,True,True,False,True,True,False,False
4,2015,2015-08-08,2015-08-08,True,True,True,True,False,True,True,False,False
2,2016,2016-08-13,2016-08-13,True,True,True,True,False,True,True,True,False
1,2017,2017-08-11,2017-08-11,True,True,True,True,False,True,True,True,True
0,2018,2018-08-10,2018-08-10,True,True,True,True,False,True,True,True,True
3,2019,2019-08-09,2019-08-09,True,True,True,True,True,True,True,True,True

We can see that we have 10 years of EPL history that we could store, and that further statistics available for the last 3 seasons at least.